import dayjs, { Dayjs } from "dayjs";
export const defaultValue = {
  saleDate : dayjs(),
  foods: {
    detail: [
      {
        id: "food1",
        item: "တာကိုရာကီ",
        qty: 0,
        price: null,
      },
      {
        id: "food2",
        item: "တော့ပိုကီ",
        qty: 0,
        price: null,
      },
      {
        id: "food3",
        item: "ငါးအသားပြား",
        qty: 0,
        price: null,
      },
      {
        id: "food4",
        item: "ငါးပေါင်မုန့်",
        qty: 0,
        price: null,
      },
      {
        id: "food5",
        item: "ဟမ်ဘာကာ",
        qty: 0,
        price: null,
      },
      {
        id: "food6",
        item: "ငုံးဥကြော်",
        qty: 0,
        price: null,
      },
    ],
    total: 0,
  },

  drinks: {
    detail: [
      {
        id: "drink1",
        item: "Ice Leamon Tea",
        normal : 0,
        soda : null,
        price: 0,
      },
      {
        id: "drink2",
        item: "Ice Peach Tea",
        normal : 0,
        soda : null,
        price: null,
      },
      {
        id: "drink3",
        item: "Thai Tea",
        normal : 0,
        soda : null,
        price: null,
      },
      {
        id: "drink4",
        item: "Green Tea",
        normal : 0,
        soda : null,
        price: null,
      },
      {
        id: "drink5",
        item: "Ice Coffee",
        normal : 0,
        soda : null,
        price: null,
      },
      {
        id: "drink6",
        item: "BlueBerry",
        normal : 0,
        soda : 0,
        price: null,
      },
      {
        id: "drink7",
        item: "Strawberry",
        normal : 0,
        soda : 0,
        price: null,
      },
      {
        id: "drink8",
        item: "Orange",
        normal : 0,
        soda : 0,
        price: null,
      },
      {
        id: "drink9",
        item: "Watermelon",
        normal : 0,
        soda : 0,
        price: null,
      },
      {
        id: "drink10",
        item: "Respberry Red",
        normal : 0,
        soda : 0,
        price: null,
      },
      {
        id: "drink11",
        item: "Respberry Blue",
        normal : 0,
        soda : 0,
        price: null,
      },
      {
        id: "drink12",
        item: "Passion Fruit",
        normal : 0,
        soda : 0,
        price: null,
      },
      {
        id: "drink13",
        item: "Pineapple",
        normal : 0,
        soda : 0,
        price: null,
      },
      {
        id: "drink14",
        item: "Green Apple",
        normal : 0,
        soda : 0,
        price: null,
      },
      {
        id: "drink15",
        item: "Peach",
        normal : 0,
        soda : 0,
        price: null,
      },
      {
        id: "drink16",
        item: "Mixed Berry",
        normal : 0,
        soda : 0,
        price: null,
      },
      {
        id: "drink17",
        item: "Grap",
        normal : 0,
        soda : 0,
        price: null,
      },
      {
        id: "drink18",
        item: "Lychee",
        normal : 0,
        soda : 0,
        price: null,
      },
      {
        id: "drink19",
        item: "Honey Drew",
        normal : 0,
        soda : 0,
        price: null,
      },
      {
        id: "drink20",
        item: "Yogurt",
        normal : 0,
        soda : 0,
        price: null,
      },

    ],
    total: 0,
  },
};
